[package]
name = "clicky"
version = "0.1.0"
authors = ["John <johnmorris@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
midir = "0.7"
wmidi = "4.0"
winit = "0.24.0"
